steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-mtgbracket:latest', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/php-mtgbracket:latest']

options:
    #machineType: N1_HIGHCPU_8

tags: ['app', 'php-mtgbracket']
images: ['gcr.io/$PROJECT_ID/php-mtgbracket']