steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-node-mtgbracket:latest', 'php-node-mtgbracket/.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/php-node-mtgbracket:latest']

options:
    machineType: N1_HIGHCPU_8

timeout: 1200s

tags: ['app', 'php-node-mtgbracket']
images: ['gcr.io/$PROJECT_ID/php-node-mtgbracket']